spring:  application:    name: service#视图映射      mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp#启用Aop        aop:
    proxy-target-class: true
#mybatis-plus配置
mybatis-plus:  type-aliases-package: cn.lcxian.pojo
  mapper-locations: classpath:/mapper/*.xml#不适用驼峰映射
  configuration:
    map-underscore-to-camel-case: false      logging:  level:     cn.lcxian.dao: debug#端口配置        
server:
  port: 80
  servlet:
    context-path: /Consult/Rest/#运行库      ---spring:  profiles: running  datasource:        #引入druid数据源    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: oracle.jdbc.OracleDriver    url: jdbc:oracle:thin:@localhost:1521:orcl    username: test    password: test    #测试库---spring:  profiles: test  datasource:        #引入druid数据源    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: org.sqlite.JDBC    url: jdbc:sqlite:D:\\CLOUDRIS.db    